# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.X]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm test
      - run: |
          LINES=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          STATEMENTS=$(jq '.total.statements.pct' coverage/coverage-summary.json)
          FUNCTIONS=$(jq '.total.functions.pct' coverage/coverage-summary.json)
          BRANCHES=$(jq '.total.branches.pct' coverage/coverage-summary.json)

            echo "COVERAGE_REPORT<<EOF" >> $GITHUB_ENV
            echo "Lines: ${LINES}%" >> $GITHUB_ENV
            echo "Statements: ${STATEMENTS}%" >> $GITHUB_ENV
            echo "Functions: ${FUNCTIONS}%" >> $GITHUB_ENV
            echo "Branches: ${BRANCHES}%" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV


      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Jest Coverage Report

      - name: Create or update coverage comment
        if: github.event_name =='pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id}}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Jest Coverage Report 📊
            ${{ env.COVERAGE_REPORT }}
          edit-mode: replace

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./  # Déploie tout le projet, y compris index.html et les fichiers JS

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
